#version 450

layout (set = 0, binding = 0, rgba8) uniform writeonly image2D image;

layout(local_size_x = 256, local_size_y = 1,local_size_z = 1) in;

layout (push_constant) uniform PushConst {
    vec4 data; // 0 -> time    1 & 2 -> resolution  3 -> padding
} pd;

void main() {
    vec2 uv = ivec2(gl_GlobalInvocationID.xy);
    vec4 color = vec4(normalize(uv * 2.0 - 1.0), 0.0, 1.0);
    imageStore(image, ivec2(gl_GlobalInvocationID.xy), color);
}